import Head from 'next/head';
import Footer from '@/src/components/card/footer';
import Header from '@/src/components/card/Header';
import MainSection from '@/src/components/card/MainSection';
import Sobre from '@/src/components/card/sobre';
import Emergencia from '@/src/components/card/emergencia';
import CadastroPet from '@/src/components/card/cadastropet';
import Cadastro from '@/src/components/card/cadastro';

export default function home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>VitalVet</title>
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
          integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
          crossOrigin="anonymous"
        />
      </Head>
      <div>
        {/* 
        <Sobre/>
        <Emergencia/>
        <Cadastro/>
        <CadastroPet/>
        <Cadastro/>*/}
        <Header/>
        <MainSection/>
        <Footer/> 
      </div>
    </>
  );
}
